# Common test helper functions for reqdrive tests

# Get the project root directory
export REQDRIVE_ROOT
REQDRIVE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Test fixtures directory
export TEST_FIXTURES
TEST_FIXTURES="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/fixtures"

# Create a temporary directory for test isolation
setup_temp_dir() {
  export TEST_TEMP_DIR
  TEST_TEMP_DIR="$(mktemp -d)"
  export ORIGINAL_PWD
  ORIGINAL_PWD="$(pwd)"
  cd "$TEST_TEMP_DIR" || exit 1
}

# Clean up temporary directory
teardown_temp_dir() {
  cd "$ORIGINAL_PWD" || exit 1
  if [ -n "$TEST_TEMP_DIR" ] && [ -d "$TEST_TEMP_DIR" ]; then
    rm -rf "$TEST_TEMP_DIR"
  fi
}

# Create a minimal valid manifest for testing
create_test_manifest() {
  local dir="${1:-.}"
  cat > "$dir/reqdrive.json" <<'EOF'
{
  "project": {
    "name": "test-project",
    "title": "Test Project"
  },
  "paths": {
    "requirementsDir": "docs/requirements",
    "agentDir": ".reqdrive/agent",
    "appDir": ".",
    "contextFile": "CLAUDE.md"
  },
  "requirements": {
    "pattern": "REQ-*-*.md",
    "idRegex": "REQ-[0-9]+",
    "dependencies": {}
  },
  "commands": {
    "install": "npm install",
    "test": "npm test",
    "typecheck": "npx tsc --noEmit",
    "lint": "npx eslint ."
  },
  "agent": {
    "model": "claude-opus-4-5-20251101",
    "maxIterations": 10,
    "branchPrefix": "reqdrive",
    "worktreePrefix": "reqdrive",
    "completionSignal": "<promise>COMPLETE</promise>"
  },
  "verification": {
    "maxRetries": 3,
    "checks": [],
    "generateTests": true
  },
  "pr": {
    "labels": ["agent-generated"],
    "reqLabel": true,
    "setupSteps": [],
    "regressionChecks": [],
    "footer": "Generated by reqdrive."
  },
  "orchestration": {
    "maxParallel": 3,
    "worktreeRoot": "../worktrees",
    "baseBranch": "main",
    "stateDir": ".reqdrive/state"
  },
  "security": {
    "mode": "interactive",
    "allowedTools": []
  }
}
EOF
}

# Create a minimal project structure
create_test_project() {
  local dir="${1:-.}"
  mkdir -p "$dir/docs/requirements"
  mkdir -p "$dir/.reqdrive/agent"
  create_test_manifest "$dir"
  echo "# Test Project" > "$dir/CLAUDE.md"
}

# Create a test requirements file
create_test_requirement() {
  local dir="${1:-.}"
  local req_id="${2:-REQ-01}"
  local req_name="${3:-Test Feature}"
  mkdir -p "$dir/docs/requirements"
  cat > "$dir/docs/requirements/${req_id}-${req_name// /-}.md" <<EOF
# ${req_id}: ${req_name}

## Description
This is a test requirement.

## Acceptance Criteria
- [ ] Feature is implemented
- [ ] Tests pass
EOF
}

# Initialize a git repository for testing
init_test_git_repo() {
  local dir="${1:-.}"
  cd "$dir" || exit 1
  git init -q
  git config user.email "test@example.com"
  git config user.name "Test User"
  git add -A
  git commit -q -m "Initial commit"
  cd - > /dev/null || exit 1
}

# Mock the claude CLI
mock_claude() {
  export PATH="$TEST_TEMP_DIR/bin:$PATH"
  mkdir -p "$TEST_TEMP_DIR/bin"
  cat > "$TEST_TEMP_DIR/bin/claude" <<'EOF'
#!/usr/bin/env bash
# Mock claude CLI for testing
echo "MOCK_CLAUDE_CALLED"
echo "Args: $*"
# Output completion signal if requested
if [[ "$*" == *"VERIFICATION_PASSED"* ]]; then
  echo "VERIFICATION_PASSED"
fi
EOF
  chmod +x "$TEST_TEMP_DIR/bin/claude"
}

# Mock the gh CLI
mock_gh() {
  export PATH="$TEST_TEMP_DIR/bin:$PATH"
  mkdir -p "$TEST_TEMP_DIR/bin"
  cat > "$TEST_TEMP_DIR/bin/gh" <<'EOF'
#!/usr/bin/env bash
# Mock gh CLI for testing
echo "MOCK_GH_CALLED"
echo "Args: $*"
if [[ "$1" == "pr" && "$2" == "create" ]]; then
  echo "https://github.com/test/test-project/pull/1"
fi
EOF
  chmod +x "$TEST_TEMP_DIR/bin/gh"
}

# Assert a file contains a string
assert_file_contains() {
  local file="$1"
  local expected="$2"
  if ! grep -q "$expected" "$file"; then
    echo "Expected file '$file' to contain: $expected"
    echo "Actual content:"
    cat "$file"
    return 1
  fi
}

# Assert a file does not contain a string
assert_file_not_contains() {
  local file="$1"
  local unexpected="$2"
  if grep -q "$unexpected" "$file"; then
    echo "Expected file '$file' to NOT contain: $unexpected"
    echo "Actual content:"
    cat "$file"
    return 1
  fi
}

# Assert environment variable is set
assert_env_set() {
  local var_name="$1"
  local expected="${2:-}"
  local actual="${!var_name}"
  if [ -z "$actual" ]; then
    echo "Expected environment variable '$var_name' to be set"
    return 1
  fi
  if [ -n "$expected" ] && [ "$actual" != "$expected" ]; then
    echo "Expected $var_name='$expected', got '$actual'"
    return 1
  fi
}
