#!/usr/bin/env bash
# pr-create.sh - Create a PR with validation checklist from PRD

# Source sanitize if not already loaded
if ! type sanitize_label &>/dev/null; then
  source "${REQDRIVE_ROOT:-$(dirname "${BASH_SOURCE[0]}")/..}/lib/sanitize.sh"
fi

create_pr() {
  local project_root="$1"
  local req="$2"
  local branch="$3"
  local base_branch="$4"
  local draft_flag="${5:-}"
  local agent_dir="${6:-}"

  # Fall back to runs dir based on req slug, then legacy path
  if [ -z "$agent_dir" ]; then
    local req_slug
    req_slug=$(echo "$req" | tr '[:upper:]' '[:lower:]')
    agent_dir="$project_root/.reqdrive/runs/$req_slug"
  fi
  local prd_file="$agent_dir/prd.json"

  # Push branch
  echo "  Pushing branch $branch..."
  git push -u origin "$branch" || {
    echo "  ERROR: Failed to push branch"
    return 1
  }

  # Extract info from PRD if it exists
  local project="$req Implementation"
  local story_count="0"
  local story_ids=""
  local checklist=""

  if [ -f "$prd_file" ]; then
    project=$(jq -r '.project // "Feature Implementation"' "$prd_file")
    story_count=$(jq '.userStories | length' "$prd_file")
    story_ids=$(jq -r '.userStories | map(.id) | join(", ")' "$prd_file")

    # Build validation checklist from acceptance criteria
    while IFS= read -r story; do
      local id title
      id=$(echo "$story" | jq -r '.id')
      title=$(echo "$story" | jq -r '.title')
      checklist+=$'\n'"### $id: $title"$'\n'
      while IFS= read -r criterion; do
        checklist+="- [ ] $criterion"$'\n'
      done < <(echo "$story" | jq -r '.acceptanceCriteria[]')
    done < <(jq -c '.userStories[]' "$prd_file")
  fi

  # Get commit summary
  local commits
  commits=$(git log --oneline "$base_branch".."$branch" 2>/dev/null || echo "No commits found")

  # Build label flags with proper sanitization
  local labels=()

  if [ -n "${REQDRIVE_PR_LABELS:-}" ]; then
    IFS=',' read -ra config_labels <<< "$REQDRIVE_PR_LABELS"
    for label in "${config_labels[@]}"; do
      local sanitized
      sanitized=$(sanitize_label "$label")
      if [ -n "$sanitized" ]; then
        labels+=("$sanitized")
      fi
    done
  fi

  # Add REQ-specific label (sanitized)
  local req_label
  req_label=$(echo "$req" | tr '[:upper:]' '[:lower:]')
  req_label=$(sanitize_label "$req_label")
  if [ -n "$req_label" ]; then
    labels+=("$req_label")
  fi

  # Build label arguments - each label properly quoted
  local label_args=()
  for label in "${labels[@]}"; do
    label_args+=("--label" "$label")
  done

  # Create PR
  echo "  Creating PR..."

  gh pr create \
    $draft_flag \
    --base "$base_branch" \
    --head "$branch" \
    "${label_args[@]}" \
    --title "$project" \
    --body "$(cat <<EOF
## Summary
- **Source:** $req
- **Branch:** \`$branch\`
- **Stories completed:** $story_ids ($story_count stories)

## Commits
\`\`\`
$commits
\`\`\`

## Validation Checklist

> Complete these checks before approving.

### Setup
- [ ] Pull branch: \`git checkout $branch\`
- [ ] Install dependencies
- [ ] Run tests locally

### Functional Verification
$checklist

### Regression Check
- [ ] Existing tests pass
- [ ] No unintended side effects

---
Generated by [reqdrive](https://github.com/anthropics/reqdrive)
EOF
  )"

  local pr_url
  pr_url=$(gh pr view "$branch" --json url --jq '.url' 2>/dev/null || echo "")

  echo "  PR created: $branch"
  [ -n "$pr_url" ] && echo "  URL: $pr_url"
  return 0
}
