#!/usr/bin/env bash
# pr-create.sh — PR creation with validation checklist from manifest config
# Sourced by run-single-req.sh

create_pr() {
  local worktree_path="$1"
  local req="$2"
  local branch="$3"
  local base_branch="$4"
  local draft_flag="${5:-}"

  local agent_dir="$worktree_path/$REQDRIVE_PATHS_AGENT_DIR"
  local prd_file="$agent_dir/prd.json"
  local manifest="$REQDRIVE_MANIFEST"

  if [ ! -f "$prd_file" ]; then
    echo "  ERROR: prd.json not found at $prd_file"
    return 1
  fi

  cd "$worktree_path"

  # Push branch
  echo "  Pushing branch $branch..."
  git push -u origin "$branch"

  # Extract info from PRD
  local project
  project=$(jq -r '.project' "$prd_file")
  local story_count
  story_count=$(jq '.userStories | length' "$prd_file")
  local story_ids
  story_ids=$(jq -r '.userStories | map(.id) | join(", ")' "$prd_file")

  # Build validation checklist from acceptance criteria
  local checklist=""
  while IFS= read -r story; do
    local id title
    id=$(echo "$story" | jq -r '.id')
    title=$(echo "$story" | jq -r '.title')
    checklist+=$'\n'"### $id: $title"$'\n'
    while IFS= read -r criterion; do
      checklist+="- [ ] $criterion"$'\n'
    done < <(echo "$story" | jq -r '.acceptanceCriteria[]')
  done < <(jq -c '.userStories[]' "$prd_file")

  # Get commit summary
  local commits
  commits=$(git log --oneline "$base_branch".."$branch" 2>/dev/null || echo "No commits found")

  # Verification report note
  local test_info=""
  if [ -f "$agent_dir/verification-report.txt" ]; then
    test_info="See verification report in PR comments."
  fi

  # Build label flags from manifest
  local label_flags=""
  local label_count
  label_count=$(jq '.pr.labels // [] | length' "$manifest")
  for i in $(seq 0 $((label_count - 1))); do
    local label
    label=$(jq -r ".pr.labels[$i]" "$manifest")
    label_flags+=" --label $label"
  done

  # Add REQ-specific label if configured
  local req_label_enabled
  req_label_enabled=$(jq -r '.pr.reqLabel // true' "$manifest")
  if [ "$req_label_enabled" = "true" ]; then
    local req_label
    req_label=$(echo "$req" | tr '[:upper:]' '[:lower:]')
    label_flags+=" --label $req_label"
  fi

  # Build setup steps from manifest
  local setup_steps=""
  local setup_count
  setup_count=$(jq '.pr.setupSteps // [] | length' "$manifest")
  for i in $(seq 0 $((setup_count - 1))); do
    local step
    step=$(jq -r ".pr.setupSteps[$i]" "$manifest")
    # Expand {branch} placeholder
    step="${step//\{branch\}/$branch}"
    setup_steps+="- [ ] $step"$'\n'
  done

  # Build regression checks from manifest
  local regression_checks=""
  local reg_count
  reg_count=$(jq '.pr.regressionChecks // [] | length' "$manifest")
  for i in $(seq 0 $((reg_count - 1))); do
    local check
    check=$(jq -r ".pr.regressionChecks[$i]" "$manifest")
    regression_checks+="- [ ] $check"$'\n'
  done

  # Footer from manifest
  local footer
  footer=$(jq -r '.pr.footer // "Generated by reqdrive."' "$manifest")

  # Create PR
  echo "  Creating PR..."
  gh pr create \
    $draft_flag \
    --base "$base_branch" \
    --head "$branch" \
    $label_flags \
    --title "$project" \
    --body "$(cat <<EOF
## Summary
- **Source:** $req
- **Branch:** \`$branch\`
- **Stories completed:** $story_ids ($story_count stories)
$test_info

## Commits
\`\`\`
$commits
\`\`\`

## User Validation Checklist

> Complete these steps manually before approving.

### Setup
$setup_steps
### Functional Verification
$checklist

### Regression Check
$regression_checks
---
$footer
EOF
  )"

  local pr_url
  pr_url=$(gh pr view "$branch" --json url --jq '.url' 2>/dev/null || echo "")

  # Post verification report as comment if it exists
  if [ -f "$agent_dir/verification-report.txt" ]; then
    echo "  Posting verification report as PR comment..."
    gh pr comment "$branch" --body "$(cat <<EOF
## Verification Report

\`\`\`
$(tail -50 "$agent_dir/verification-report.txt")
\`\`\`
EOF
    )" 2>/dev/null || echo "  Warning: Could not post verification report comment"
  fi

  echo "  PR created for $branch"
  [ -n "$pr_url" ] && echo "  URL: $pr_url"
  return 0
}
