{
  "project": {
    "name": "{{PROJECT_NAME}}",
    "title": "{{PROJECT_TITLE}}"
  },
  "paths": {
    "requirementsDir": "docs/requirements",
    "agentDir": ".reqdrive/agent",
    "appDir": ".",
    "contextFile": "CLAUDE.md"
  },
  "requirements": {
    "pattern": "REQ-*-*.md",
    "idRegex": "REQ-[0-9]+",
    "dependencies": {}
  },
  "commands": {
    "install": "npm install",
    "test": "npm test",
    "typecheck": null,
    "lint": null
  },
  "agent": {
    "model": "claude-opus-4-5-20251101",
    "maxIterations": 10,
    "branchPrefix": "reqdrive",
    "worktreePrefix": "reqdrive",
    "completionSignal": "<promise>COMPLETE</promise>"
  },
  "verification": {
    "maxRetries": 3,
    "checks": [],
    "generateTests": true
  },
  "pr": {
    "labels": ["agent-generated", "needs-validation"],
    "reqLabel": true,
    "setupSteps": [
      "Pull branch: `git checkout {branch}`",
      "Install deps: `npm install`"
    ],
    "regressionChecks": [
      "Existing features still work",
      "No console errors",
      "Tests pass locally"
    ],
    "footer": "Generated by reqdrive."
  },
  "orchestration": {
    "maxParallel": 3,
    "worktreeRoot": "../worktrees",
    "baseBranch": "main",
    "stateDir": ".reqdrive/state"
  },
  "security": {
    "mode": "interactive",
    "allowedTools": []
  }
}
